apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.100
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
    - protocol: UDP
      port: 53
      targetPort: 53
