apiVersion: v1
kind: Service
metadata:
  name: dns-udp-svc-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.100
  ports:
    - protocol: UDP
      name: dns-udp
      port: 53
      targetPort: 53
