apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## PrefixSuffixTransformer
namePrefix: prod-

## NamespaceTransformer
namespace: prod

## LabelTransformer
commonLabels:
  environment: prod

## ImageTagTransformer
images:
- name: nginx
  newTag: stable

## ReplicaCountTransformer - not supported in kubectl kustomize or kubectl apply -k
# replicas:
# - count: 3
#   name: nginx

## ConfigMapGenerator
configMapGenerator:
- literals:
  - NGINX_VERSION=stable
  name: nginx-config

bases:
- ../../base
