apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## PrefixSuffixTransformer
namePrefix: dev-

## NamespaceTransformer
namespace: dev

## LabelTransformer
commonLabels:
  environment: dev

## ImageTagTransformer
images:
- name: nginx
  newTag: 1.17.3

bases:
- ../../base
