apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: intro-nginx # Название контейнера
      image: antoniv1061/intro-nginx:0.1 # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: "/app"
  initContainers:
    - name: install
      image: busybox:latest
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}
